[package]
name = "rust-lib"
version = "0.1.0"
authors = ["Johan Planchon <johan.planchon@simplx.fr>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
nom = "^6.1"
wasm-bindgen = { version = "^0.2", features = ["serde-serialize"] }
serde = { version = "^1.0", features = ["derive"] }
